# Site settings
title: Your Pleasant Grove
email: cory@coryklein.com
description: > # this means to ignore newlines until "baseurl:"
    Voter guide for Pleasant Grove elections
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourpleasantgrove.com" # the base hostname & protocol for your site
twitter_username: yourpleasantgrove
github_username:  yourpleasantgrove
facebook_username:  Your-Pleasant-Grove-252821628566931

# Build settings
markdown: kramdown
